backend:
  name: github
  repo: nasplayer/my-blog
  branch: main
  base_url: https://cms-oauth.nasplayer.workers.dev
  auth_endpoint: auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "草稿", name: "draft", widget: "boolean", default: false}
      - {label: "标签", name: "tags", widget: "list", default: []}
      - {label: "分类", name: "categories", widget: "list", default: []}
      - {label: "正文", name: "body", widget: "markdown"}
